import type {Metadata} from "next";

import "./globals.css";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "ab-rsc",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4">
        <Header />
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[3rem] opacity-70">
          © {new Date().getFullYear()} ab-rsc
        </footer>
      </body>
    </html>
  );
}
